sudo: false

cache: bundler

language: ruby

rvm:
- 2.2.2

install:
- bundle  
- . $HOME/.nvm/nvm.sh
- nvm install 5.0
- nvm use 5.0
- npm install tldr-lint

gemfile:
- Gemfile

script:
- make lint

after_success:
- bash scripts/build.sh

env:
  global:
  - secure: ewQMcFd3wH8IHOeGhIkBr2kAgadONmesv2KB+9bPRCZ5gvtFFwlkCMdPnQBR9Kd3GKC8r+EO0JNNFWOvrDjPYhEHi9Ab26Q/qodwfwne9YloKXT+C48Zrbrj8q7kb/FeMYPev+RMuM96j5E5QyqBVohGP7hC2bpU3mvAhQ2wBCE=
